include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  exclude:
    - lib/firebase_options_dev.dart
    - lib/firebase_options_prod.dart
