<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="tile_clouds_v02" tilewidth="64" tileheight="64" spacing="4" tilecount="72" columns="8">
 <image source="tile_clouds_v02.png" width="544" height="612"/>
 <tile id="0" type="Platform"/>
 <tile id="1" type="Platform"/>
 <tile id="2" type="Platform"/>
 <tile id="3" type="Platform"/>
 <tile id="4" type="Platform"/>
 <tile id="5" type="Platform"/>
 <tile id="6" type="Platform"/>
 <tile id="7" type="Platform"/>
 <tile id="8" type="Platform"/>
 <tile id="9" type="Platform"/>
 <tile id="10" type="Platform"/>
 <tile id="11" type="Platform"/>
 <tile id="12" type="Platform"/>
 <tile id="13" type="Platform"/>
 <tile id="14" type="Platform"/>
 <tile id="15" type="Platform"/>
 <tile id="16" type="Platform"/>
 <tile id="17" type="Platform"/>
 <tile id="18" type="Platform"/>
 <tile id="19" type="Platform"/>
 <tile id="20" type="Platform"/>
 <tile id="21" type="Platform"/>
 <tile id="22" type="Platform"/>
 <tile id="23" type="Platform"/>
 <tile id="24" type="Platform"/>
 <tile id="25" type="Platform"/>
 <tile id="26" type="Platform"/>
 <tile id="27" type="Platform"/>
 <tile id="28" type="Platform"/>
 <tile id="29" type="Platform"/>
 <tile id="30" type="Platform"/>
 <tile id="31" type="Platform"/>
 <tile id="32" type="Platform"/>
 <tile id="33" type="Platform"/>
 <tile id="34" type="Platform"/>
 <tile id="35" type="Platform"/>
 <tile id="36" type="Platform"/>
 <tile id="37" type="Platform"/>
 <tile id="38" type="Platform"/>
 <tile id="39" type="Platform"/>
 <tile id="40" type="Platform"/>
 <tile id="41" type="Platform"/>
 <tile id="42" type="Platform"/>
 <tile id="43" type="Platform"/>
 <tile id="44" type="Platform"/>
 <tile id="45" type="Platform"/>
 <tile id="46" type="Platform"/>
 <tile id="47" type="Platform"/>
 <tile id="48" type="Platform"/>
 <tile id="49" type="Platform"/>
 <tile id="50" type="Platform"/>
 <tile id="51" type="Platform"/>
 <tile id="52" type="Platform"/>
 <tile id="53" type="Platform"/>
 <tile id="54" type="Platform"/>
 <tile id="55" type="Platform"/>
 <tile id="56" type="Platform"/>
 <tile id="57" type="Platform"/>
 <tile id="58" type="Platform"/>
 <tile id="59" type="Platform"/>
 <tile id="60" type="Platform"/>
 <tile id="61" type="Platform"/>
 <tile id="62" type="Platform"/>
 <tile id="63" type="Platform"/>
 <tile id="64" type="Platform"/>
 <tile id="65" type="Platform"/>
 <tile id="66" type="Platform"/>
 <tile id="67" type="Platform"/>
 <tile id="68" type="Platform"/>
 <tile id="69" type="Platform"/>
 <tile id="70" type="Platform"/>
 <tile id="71" type="Platform"/>
</tileset>
