// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmOMgwQhWPWkkEbO3fnkLyD8gr_UUTYzg',
    appId: '1:1181695468:web:922d7b2091a23d3293d4c9',
    messagingSenderId: '1181695468',
    projectId: 'dash-run-dev',
    authDomain: 'dash-run-dev.firebaseapp.com',
    storageBucket: 'dash-run-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoXh3jeHcJIUFdtAlgwKxkM7Oygo5_ok8',
    appId: '1:1181695468:android:e12ffa11408de53693d4c9',
    messagingSenderId: '1181695468',
    projectId: 'dash-run-dev',
    storageBucket: 'dash-run-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhA6hFKpTmF0SxflCWUH80Sb_7E8tH8Kw',
    appId: '1:1181695468:ios:7d55d35084fe5b5a93d4c9',
    messagingSenderId: '1181695468',
    projectId: 'dash-run-dev',
    storageBucket: 'dash-run-dev.appspot.com',
    iosBundleId: 'com.vgv.superDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhA6hFKpTmF0SxflCWUH80Sb_7E8tH8Kw',
    appId: '1:1181695468:ios:68ee2f8cc077ef2a93d4c9',
    messagingSenderId: '1181695468',
    projectId: 'dash-run-dev',
    storageBucket: 'dash-run-dev.appspot.com',
    iosBundleId: 'com.example.dashRun.RunnerTests',
  );
}
