<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="spritesheet_dash_deathDrown" tilewidth="64" tileheight="64" tilecount="80" columns="8">
 <image source="spritesheet_dash_deathDrown.png" width="512" height="640"/>
 <tile id="0">
  <animation>
   <frame tileid="0" duration="42"/>
   <frame tileid="1" duration="42"/>
   <frame tileid="2" duration="42"/>
   <frame tileid="3" duration="42"/>
   <frame tileid="4" duration="42"/>
   <frame tileid="5" duration="42"/>
   <frame tileid="6" duration="42"/>
   <frame tileid="7" duration="42"/>
   <frame tileid="8" duration="42"/>
   <frame tileid="9" duration="42"/>
   <frame tileid="10" duration="42"/>
   <frame tileid="11" duration="42"/>
   <frame tileid="12" duration="42"/>
   <frame tileid="13" duration="42"/>
   <frame tileid="14" duration="42"/>
   <frame tileid="15" duration="42"/>
   <frame tileid="16" duration="42"/>
   <frame tileid="17" duration="42"/>
   <frame tileid="18" duration="42"/>
   <frame tileid="19" duration="42"/>
   <frame tileid="20" duration="42"/>
   <frame tileid="21" duration="42"/>
   <frame tileid="22" duration="42"/>
   <frame tileid="23" duration="42"/>
   <frame tileid="24" duration="42"/>
   <frame tileid="25" duration="42"/>
   <frame tileid="26" duration="42"/>
   <frame tileid="27" duration="42"/>
   <frame tileid="28" duration="42"/>
   <frame tileid="29" duration="42"/>
   <frame tileid="30" duration="42"/>
   <frame tileid="31" duration="42"/>
   <frame tileid="32" duration="42"/>
   <frame tileid="33" duration="42"/>
   <frame tileid="34" duration="42"/>
   <frame tileid="35" duration="42"/>
   <frame tileid="36" duration="42"/>
   <frame tileid="37" duration="42"/>
   <frame tileid="38" duration="42"/>
   <frame tileid="39" duration="42"/>
   <frame tileid="40" duration="42"/>
   <frame tileid="41" duration="42"/>
   <frame tileid="42" duration="42"/>
   <frame tileid="43" duration="42"/>
   <frame tileid="44" duration="42"/>
   <frame tileid="45" duration="42"/>
   <frame tileid="46" duration="42"/>
   <frame tileid="47" duration="42"/>
   <frame tileid="48" duration="42"/>
   <frame tileid="49" duration="42"/>
   <frame tileid="50" duration="42"/>
   <frame tileid="51" duration="42"/>
   <frame tileid="52" duration="42"/>
   <frame tileid="53" duration="42"/>
   <frame tileid="54" duration="42"/>
   <frame tileid="55" duration="42"/>
   <frame tileid="56" duration="42"/>
   <frame tileid="57" duration="42"/>
   <frame tileid="58" duration="42"/>
   <frame tileid="59" duration="42"/>
   <frame tileid="60" duration="42"/>
   <frame tileid="61" duration="42"/>
   <frame tileid="62" duration="42"/>
   <frame tileid="63" duration="42"/>
   <frame tileid="64" duration="42"/>
   <frame tileid="65" duration="42"/>
   <frame tileid="66" duration="42"/>
   <frame tileid="67" duration="42"/>
   <frame tileid="68" duration="42"/>
   <frame tileid="69" duration="42"/>
   <frame tileid="70" duration="42"/>
   <frame tileid="71" duration="42"/>
   <frame tileid="72" duration="42"/>
   <frame tileid="73" duration="42"/>
   <frame tileid="74" duration="42"/>
   <frame tileid="75" duration="42"/>
   <frame tileid="76" duration="42"/>
   <frame tileid="77" duration="42"/>
   <frame tileid="78" duration="42"/>
   <frame tileid="79" duration="42"/>
  </animation>
 </tile>
</tileset>
